version: '3'
services:
  web:
    user: 1000:1000
    restart: always
    env_file:
      - .env
    build: .
    command: >
      bash -c "python wait_for_db.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
