# Generated by Django 3.2.7 on 2021-09-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiary',
            options={'verbose_name': 'Apiary', 'verbose_name_plural': 'Apiaries'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='hive',
            options={'verbose_name': 'Hive', 'verbose_name_plural': 'Hives'},
        ),
    ]
