# Generated by Django 3.2.7 on 2021-09-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0002_auto_20210930_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hive',
            field=models.OneToOneField(blank=True, help_text='Hive where the device is located', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bees.hive'),
        ),
    ]
